        new Vue({
            el: '#app',
            data: {
                memberFilter: 'BiS',//初期表示
                projects: [
                { title: "", title2: "23.09.18 HMV&BOOKS HAKATA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/shion15.webp", category: 'SHiON' },
                { title: "", title2: "23.09.18 HMV&BOOKS HAKATA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy26.webp", category: 'TOGGY' },
                { title: "", title2: "23.09.18 HMV&BOOKS HAKATA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy25.webp", category: 'TOGGY' },
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/mugen2.webp", category: 'MUGEN' }, 
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/kure3.webp", category: 'KURE' }, 
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy24.webp", category: 'TOGGY' },
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano25.webp", category: 'NANO3' }, 
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy23.webp", category: 'TOGGY' }, 
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/hyuga6.webp", category: 'HYUGA' },
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy22.webp", category: 'TOGGY' },
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano24.webp", category: 'NANO3' },   
                { title: "", title2: "23.09.17 FUKUOKA DRUM Be-1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy21.webp", category: 'TOGGY' },    
                { title: "", title2: "23.07.16 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy18.webp", category: 'TOGGY' },
                { title: "", title2: "23.07.16 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion14.webp", category: 'SHiON' },
                { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion13.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion12.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion11.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion10.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion9.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion8.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion7.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.15 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion5.webp", category: 'SHiON' },
                    { title: "", title2: "23.07.14 TOWER RECORD KINSHICHO PARCO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy17.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy16.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/kure2.webp", category: 'KURE' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano20.webp", category: 'NANO3' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/kure.webp", category: 'KURE' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy15.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion3.webp", category: 'SHiON' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano21.webp", category: 'NANO3' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy14.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/hyuga5.webp", category: 'HYUGA' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy13.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.28 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/mugen.webp", category: 'MUGEN' },
                    { title: "", title2: "23.05.27 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy12.webp", category: 'TOGGY' },
                    { title: "", title2: "23.05.27 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano19.webp", category: 'NANO3' },
                    { title: "", title2: "23.05.27 FUKUOKA DRUM SON", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion1.webp", category: 'SHiON' },
                    { title: "", title2: "23.05.26 ESP ENTERTAINMENT FUKUOKA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS7.webp", category: 'BiS' },
                    { title: "", title2: "23.05.26 ESP ENTERTAINMENT FUKUOKA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano18.webp", category: 'NANO3' },
                    { title: "", title2: "23.05.26 ESP ENTERTAINMENT FUKUOKA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/sion2.webp", category: 'SHiON' },
                    { title: "", title2: "23.05.26 ESP ENTERTAINMENT FUKUOKA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano17.webp", category: 'NANO3' },
                    { title: "", title2: "23.03.18 SANUKI ROCK COLOSSEUM", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano15.webp", category: 'NANO3' },
                    { title: "", title2: "23.01.18 SANUKI ROCK COLOSSEUM", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy11.webp", category: 'TOGGY' },
                    { title: "", title2: "23.01.16 NAGOYA BOTTOM LINE", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/hyuga4.webp", category: 'HYUGA' },
                    { title: "", title2: "23.01.16 NAGOYA BOTTOM LINE", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy10.webp", category: 'TOGGY' },
                    { title: "", title2: "23.01.08 日比谷野外音楽堂", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS5.webp", category: 'BiS' },
                    { title: "", title2: "23.01.08 日比谷野外音楽堂", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo10.webp", category: 'NEOTREES' },
                    { title: "", title2: "23.01.08 日比谷野外音楽堂", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS4.webp", category: 'BiS' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano14.webp", category: 'NANO3' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS3.webp", category: 'BiS' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo9.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano13.webp", category: 'NANO3' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/ito6.webp", category: 'MUSENSiTEEBU' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo8.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.12.17 OSAKA BIG CAT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo7.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.12.04 SHIBUYA TOWER RECORD CUTUP STUDIO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS2.webp", category: 'BiS' },
                    { title: "", title2: "22.11.20 KUMAMOTO B.9 V1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano12.webp", category: 'NANO3' },
                    { title: "", title2: "22.11.20 KUMAMOTO B.9 V1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy7.webp", category: 'TOGGY' },
                    { title: "", title2: "22.11.20 KUMAMOTO B.9 V1", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/ito5.webp", category: 'MUSENSiTEEBU' },
                    { title: "", title2: "22.11.19 KAGOSHIMA SR HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano11.webp", category: 'NANO3' },
                    { title: "", title2: "22.11.05 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy9.webp", category: 'TOGGY' },
                    { title: "", title2: "22.11.05 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy8.webp", category: 'TOGGY' },
                    { title: "", title2: "22.11.05 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo11.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.11.05 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy6.webp", category: 'TOGGY' },
                    { title: "", title2: "22.11.05 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo6.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.11.04 KYOTO KBS HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS1.webp", category: 'BiS' },
                    { title: "", title2: "22.10.29 SHINJUKU MARUI MEN", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy19.webp", category: 'TOGGY' },
                    { title: "", title2: "22.10.29 SHINJUKU MARUI MEN", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano10.webp", category: 'NANO3' },
                    { title: "", title2: "22.10.29 SHINJUKU MARUI MEN", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo12.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.10.29 SHINJUKU MARUI MEN", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano9.webp", category: 'NANO3' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy5.webp", category: 'TOGGY' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo5.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy4.webp", category: 'TOGGY' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano23.webp", category: 'NANO3' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo14.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/ito4.webp", category: 'MUSENSiTEEBU' },
                    { title: "", title2: "22.10.16 YOKOHAMA BAY HALL", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy20.webp", category: 'TOGGY' },
                    { title: "", title2: "22.09.19 TOWER RECORD SAPPORO PARCO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy3.webp", category: 'TOGGY' },
                    { title: "", title2: "22.08.07 KAMEIDO CLOCK", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/toggy1.webp", category: 'TOGGY' },
                    { title: "", title2: "22.07.06 KAWASAKI CLUB CITTA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano7.webp", category: 'NANO3' },
                    { title: "", title2: "22.07.06 KAWASAKI CLUB CITTA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano6.webp", category: 'NANO3' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano5.webp", category: 'NANO3' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano3.webp", category: 'NANO3' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo2.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS6.webp", category: 'BiS' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo3.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.06.19 NAGASAKI DRUM Be-7", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/mon3.webp", category: 'CHANTMONKEE' },
                    { title: "", title2: "22.06.05 OKINAWA OUTPUT", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/ito1.webp", category: 'MUSENSiTEEBU' },
                    { title: "", title2: "22.03.12 MORIOKA CLUB WAVE", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/nano1.webp", category: 'NANO3' },
                    { title: "", title2: "22.03.12 MORIOKA CLUB WAVE", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo1.webp", category: 'NEOTREES' },
                    { title: "", title2: "22.03.12 MORIOKA CLUB WAVE", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/mon2.webp", category: 'CHANTMONKEE' },
                    { title: "", title2: "22.01.22 ZEPP NAGOYA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS14.webp", category: 'BiS' },
                    { title: "", title2: "22.01.19 ZEPP HANEDA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS13.webp", category: 'BiS' },
                    { title: "", title2: "21.12.12 TOKYO Spotify O-EAST", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS12.webp", category: 'BiS' },
                    { title: "", title2: "21.12.12 TOKYO Spotify O-EAST", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/neo13.webp", category: 'NEOTREES' },
                    { title: "", title2: "21.11.18 ZEPP TOKYO", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS11.webp", category: 'BiS' },
                    { title: "", title2: "21.10.23 NAKANO SUNPLAZA", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS10.webp", category: 'BiS' },
                    { title: "", title2: "21.07.17 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS9.webp", category: 'BiS' },
                    { title: "", title2: "21.07.17 KANAZAWA AZ", image: "https://raw.githubusercontent.com/NekoUX/v-BiS/main/BiS8.webp", category: 'BiS' },
                ]
            },
            computed: {
        reversedProjects() {
            return this.projects.slice().reverse();
        }
    },
            methods: {
                setMember: function (member) {
                    this.memberFilter = member;
                }
            }
        })